package com.ez.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
public class User implements Serializable {
    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private Long id;
    private String email;

    // JsonProperty.Access.WRITE_ONLY:
    // the property may only be written (set) as part of deserialization
    // (using "setter" method, or assigning to Field, or passed as Creator argument) but will not be read (get) for serialization
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String firstName;
    private String lastName;
    private String phone;
    private String address;

    // ROLE_CUSTOMER, ROLE_SUPPORTER, ROLE_ADMIN
    private String role;

    // Active or Inactive
    private String status;

}
