package com.ez.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
public class User implements Serializable {

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    // WRITE_ONLY: only allow write(set) value of id, but do not allow read id
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Long id;
//    private String userId;
    private String email;
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String firstName;
    private String lastName;
    private String phone;
    private String address;
    private String role; // ROLE_CUSTOMER, ROLE_SUPPORTER, ROLE_ADMIN
    private boolean isActive;
//    private String username;
    // WRITE_ONLY: only allow write(set) value of id, but do not allow read id
//    private String profileImageUrl;
    private Date lastLoginDate;
    private Date lastLoginDateDisplay;
    private Date joinDate;
//    private String[] authorities;

}
